# Generated by Django 4.0.6 on 2022-07-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('interval', models.CharField(choices=[('ANNUALLY', 'Annually'), ('SEMI ANNUALLY', 'Semi Annually'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='ANNUALLY', max_length=13)),
                ('date', models.DateField()),
                ('next_date', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedule',
            },
        ),
    ]
