# Generated by Django 4.0.6 on 2022-07-29 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be of 10 digit 98XXXXXXXX', regex='^98\\d{8}$')]),
        ),
    ]
